/*
 * @Author: 张淦
 * @Date: 2019-12-09 16:59:16
 * @LastEditors: zhanggan
 * @Description: 商户2.0
 * @FilePath: /gpay-ops-static/src/store/getters.js
 */
export default {
  accountList: (state) => state.accountList,
  channelList: (state) => state.channelList,
  bankList: (state) => state.bankList,
  payConfigList: (state) => state.payConfigList,
  effectLoading: (state) => state.effectLoading,
  dialogVisible: (state) => state.dialogVisible,
  roleList: (state) => state.roleList,
  dictionaryList: (state) => state.dictionaryList,
  companyList: (state) => state.companyList,
  financeList: (state) => state.financeList,
  businessList: (state) => state.businessList,
  currencyList: (state) => state.currencyList,
  businessAdministration: (state) => state.businessAdministration,
  paymentAccountList: (state) => state.paymentAccountList,
  merchantChannelList: (state) => state.merchantChannelList,
  merchantList: (state) => state.merchantList,
  accountChannel: (state) => state.accountChannel,
  paymentChannel: (state) => state.paymentChannel,
  configureList: (state) => state.configureList,
  permissionsList: (state) => state.permissionsList,
  businessNumber: (state) => state.businessNumber,
  timeNumber: (state) => state.timeNumber,
  businessLine: (state) => state.businessLine,
  payWayList: (state) => state.payWayList,
  orderStatus: (state) => state.orderStatus,
  refundStatus: (state) => state.refundStatus,
  callBackStatus: (state) => state.callBackStatus,
  bizCategory: (state) => state.bizCategory,
  enterpriseList: (state) => state.enterpriseList,
  hospitalDetail: (state) => state.hospitalDetail,
  medicalTypeList: (state) => state.medicalTypeList,
  sureStatus: (state) => state.sureStatus,
  medicalCenterList: (state) => state.medicalCenterList,
  bindCardWhiteList: (state) => state.bindCardWhiteList,
  certificatesList: (state) => state.certificatesList,
  otherChannelList: (state) => state.otherChannelList,
  doctorList: (state) => state.doctorList,
  departmentList: (state) => state.departmentList,
  bizInvoiceList: (state) => state.bizInvoiceList,
  exportList: (state) => state.exportList,
  partnerList: (state) => state.partnerList,
  fundStatistics: (state) => state.fundStatistics,
  channelConfigList: (state) => state.channelConfigList,
  HAChannel: (state) => state.HAChannel,
  HACodeList: (state) => state.HACodeList,
  checkingAccountList: (state) => state.checkingAccountList,
  allInstitution: (state) => state.allInstitution,
};
