/*
 * @Author: 张淦
 * @Date: 2019-12-09 16:59:16
 * @LastEditors: zhanggan
 * @Description: 商户2.0
 * @FilePath: /gpay-ops-static/src/store/types.js
 */

export default {
  // fetch loading
  EFFECT_LOADING: "EFFECT_LOADING",

  // dialog Visible
  DIALOG_VISIBLE: "DIALOG_VISIBLE",

  // 收款账号
  ACCOUNT_NO: "ACCOUNT_NO",

  // 账号和支付配置
  ACCOUNT_CHANNEL: "ACCOUNT_CHANNEL",
  PAYMENT_CHANNEL: "PAYMENT_CHANNEL",
  CONFIGURE_LIST: "CONFIGURE_LIST",

  // 清算分账模块
  GET_ACCOUNT_LIST: "GET_ACCOUNT_LIST",
  GET_CHANNEL_LIST: "GET_CHANNEL_LIST",
  GET_BANK_LIST: "GET_BANK_LIST",
  GET_PAYCONFIG_LIST: "GET_PAYCONFIG_LIST",

  // 商户系统模块
  GET_ROLE_LIST: "GET_ROLE_LIST",
  GET_DICTIONARY_LIST: "GET_DICTIONARY_LIST",
  GET_COMPANY_LIST: "GET_COMPANY_LIST",
  GET_FINANCE_LIST: "GET_FINANCE_LIST",
  GET_BIZ_INVOICE: "GET_BIZ_INVOICE",
  GET_BUSINESS_LIST: "GET_BUSINESS_LIST",
  GET_CURRENCY_LIST: "GET_CURRENCY_LIST",
  GET_BUSINESS_ADMINISTRATION_LIST: "GET_BUSINESS_ADMINISTRATION_LIST",
  GET_PAYMENT_ACCOUNT_LIST: "GET_PAYMENT_ACCOUNT_LIST",
  GET_MERCHANT_ALL_CHANNEL: "GET_MERCHANT_ALL_CHANNEL",
  GET_MERCHANT_CHANNEL_LIST: "GET_MERCHANT_CHANNEL_LIST",
  GET_MERCHANT_LIST: "GET_MERCHANT_LIST",
  GET_BUSINESS_NUMBER: "GET_BUSINESS_NUMBER",
  GET_TIME_NUMBER: "GET_TIME_NUMBER",
  GET_BUSINESS_LINE: "GET_BUSINESS_LINE",
  GET_PAY_MERCHANT_CHANNEL_LIST: "GET_PAY_MERCHANT_CHANNEL_LIST",
  GET_PAYWAY_LIST: "GET_PAYWAY_LIST",
  GET_ORDER_STATUS: "GET_ORDER_STATUS",
  GET_REFUND_STATUS: "GET_REFUND_STATUS",
  GET_CALLBACK_STATUS: "GET_CALLBACK_STATUS",
  GET_OTHER_CHANNEL_LIST: "GET_OTHER_CHANNEL_LIST",

  // 用户角色
  USER_ROLES: "USER_ROLES",

  // 商户入驻信息
  GET_ENTRY_INFO: "GET_ENTRY_INFO",
  GET_ADUIT_STATUS: "GET_ADUIT_STATUS",

  // 上传预览
  DIALOG_PREVIEW_STATUS: "DIALOG_PREVIEW_STATUS",
  // 业务类型列表
  GET_BIZ_CATEGORY: "GET_BIZ_CATEGORY",

  // 发票管理
  GET_ENTERPRISE_LIST: "GET_ENTERPRISE_LIST",

  // 医保后台
  GET_HOSPITAL_DETAIL: "GET_HOSPITAL_DETAIL",
  MEDICAL_TYPE_LIST: "MEDICAL_TYPE_LIST",
  GET_SURE_STATUS: "GET_SURE_STATUS",
  MEDICAL_CENTER_LIST: "MEDICAL_CENTER_LIST",
  BIND_CARD_WHITE_LIST: "BIND_CARD_WHITE_LIST",
  CERTIFICATES_LIST: "CERTIFICATES_LIST",
  DOCTOR_LIST: "DOCTOR_LIST",
  DEPARTMENT_LIST: "DEPARTMENT_LIST",
  EXPORT_LIST: "EXPORT_LIST",
  PARTNER_LIST: "PARTNER_LIST",
  FUND_STATISTICS: "FUND_STATISTICS",
  CHANNEL_CONFIG_LIST: "CHANNEL_CONFIG_LIST",

  // 健康账户后台
  GET_HA_CHANNEL: "GET_HA_CHANNEL",
  GET_HA_CODE_LIST: "GET_HA_CODE_LIST",

  // 对账 - 结算账户
  CHECKING_ACCOUNT_LIST: "CHECKING_ACCOUNT_LIST",
  GET_ALL_INSTITUTION: "GET_ALL_INSTITUTION",
};
