// 目录配置
const menus = [
  {
    name: "首页",
    uid: "/",
    icon: "nav-book",
    type: 2,
    path: "home",
  },
  //   {
  //     name: '机构入驻',
  //     path: 'enterApply',
  //     icon: 'nav-doctor-advice',
  //     uid: '/enterApply',
  //     type: 2,
  //   },
  //   {
  //     name: '机构业务管理',
  //     path: 'business',
  //     icon: 'nav-customer',
  //     uid: '/business',
  //     type: 2,
  //     children: [
  //       {
  //         name: '机构业务',
  //         path: 'list',
  //         uid: '/business/list',
  //         type: 2,
  //       },
  //       {
  //         name: '机构业务审核',
  //         path: 'audit',
  //         uid: '/business/audit',
  //         type: 2,
  //       },
  //     ],
  //   },
  {
    name: "渠道账号管理",
    path: "channel",
    icon: "nav-total-check",
    uid: "/channel",
    type: 2,
    children: [
      {
        name: "收款账号列表",
        path: "collectionList",
        uid: "/channel/collectionList",
        type: 2,
      },
      {
        name: "产品开通申请",
        path: "productApplyList",
        uid: "/channel/productApplyList",
        type: 2,
      },
      {
        name: "渠道管理",
        path: "list",
        uid: "/channel/list",
        type: 2,
      },
    ],
  },
  //   {
  //     name: '订单管理',
  //     path: 'order',
  //     icon: 'nav-inquiry',
  //     uid: '/order',
  //     type: 2,
  //     children: [
  //       {
  //         name: '支付流水',
  //         path: 'list',
  //         uid: '/order/list',
  //         type: 2,
  //       },
  //       {
  //         name: '退款流水',
  //         path: 'refund',
  //         uid: '/order/refund',
  //         type: 2,
  //       },
  //     ],
  //   },
  {
    name: "系统管理",
    path: "system",
    icon: "nav-settings",
    uid: "/system",
    type: 2,
    children: [
      {
        name: "字典管理",
        path: "dictionary",
        uid: "/system/dictionary",
        type: 2,
      },
      {
        name: "参数管理",
        path: "parameter",
        uid: "/system/parameter",
      },
      // {
      //   name: '人员管理',
      //   path: 'person',
      //   uid: '',
      // },
    ],
  },
  // {
  //   name: '清算分账管理',
  //   path: 'divideaccount',
  //   icon: 'nav-work-order',
  //   uid: '/divideaccount',
  //   type: 2,
  //   children: [
  //     {
  //       name: '分账商户管理',
  //       path: 'accountMerchants',
  //       uid: '/divideaccount/accountMerchants',
  //       type: 2,
  //     },
  //     {
  //       name: '银行卡管理',
  //       path: 'bankcardManage',
  //       uid: '/divideaccount/bankcardManage',
  //       type: 2,
  //     },
  //     {
  //       name: '商户余额管理',
  //       path: 'mercbalance',
  //       uid: '/divideaccount/mercbalance',
  //       type: 2,
  //     },
  //     {
  //       name: '分账流水查询',
  //       path: 'settleaccount',
  //       uid: '/divideaccount/settleaccount',
  //       type: 2,
  //     },
  //     {
  //       name: '结算记录查询',
  //       path: 'settlerecord',
  //       uid: '/divideaccount/settlerecord',
  //       type: 2,
  //     },
  //   ],
  // },
  {
    name: "对账管理",
    path: "checkaccount",
    icon: "nav-role",
    uid: "/checkaccount",
    type: 2,
    children: [
      {
        name: "资金对账",
        path: "fundlist",
        uid: "/checkaccount/fundlist",
        type: 2,
      },
      {
        name: "医保对账",
        path: "insurance",
        uid: "/checkaccount/insurance",
        type: 2,
      },
      {
        name: "对账统计",
        path: "statistic",
        uid: "/checkaccount/statistic",
        type: 2,
      },
      {
        name: "渠道账单文件",
        path: "channelfile",
        uid: "/checkaccount/channelfile",
        type: 2,
      },
      {
        name: "医保账单文件",
        path: "insurancefile",
        uid: "/checkaccount/insurancefile",
        type: 2,
      },
      {
        name: "收银台账单文件",
        path: "paymentfile",
        uid: "/checkaccount/paymentfile",
        type: 2,
      },
      {
        name: "渠道账号配置",
        path: "fundconfig",
        uid: "/checkaccount/fundconfig",
        type: 2,
      },
    ],
  },
  {
    name: "发票管理",
    path: "invoice",
    icon: "nav-charge",
    uid: "/invoice",
    type: 2,
    children: [
      {
        name: "发票订单管理",
        path: "order",
        uid: "/invoice/order",
        type: 2,
      },
      {
        name: "红字发票管理",
        path: "red",
        uid: "/invoice/red",
        type: 2,
      },
      {
        name: "开票企业管理",
        path: "company",
        uid: "/invoice/company",
        type: 2,
      },
    ],
  },
  {
    name: "医保管理",
    path: "insurance",
    icon: "nav-medical-insure",
    uid: "/insurance",
    type: 2,
    children: [
      //   {
      //     name: '结算流水',
      //     path: 'settlement',
      //     uid: '/insurance/settlement',
      //     type: 2,
      //   },
      {
        name: "医保中心管理",
        path: "center",
        uid: "/insurance/center",
        type: 2,
      },
      {
        name: "医疗机构管理",
        path: "institute",
        uid: "/insurance/institute",
        type: 2,
      },
      {
        name: "操作人管理",
        path: "operator",
        uid: "/insurance/operator",
        type: 2,
      },
      {
        name: "参保人管理",
        path: "card",
        uid: "/insurance/card",
        type: 2,
      },
      {
        name: "电话签约管理",
        path: "bindcard",
        uid: "/insurance/bindcard",
        type: 2,
      },
      {
        name: "电子凭证管理",
        path: "certificates",
        uid: "/insurance/certificates",
        type: 2,
      },
      {
        name: "医生管理",
        path: "doctor",
        uid: "/insurance/doctor",
        type: 2,
      },
      {
        name: "科室管理",
        path: "department",
        uid: "/insurance/department",
        type: 2,
      },
      {
        name: "医保数据下载",
        path: "department",
        uid: "/insurance/download",
        type: 2,
      },
    ],
  },
  {
    name: "健康账户管理",
    path: "healthaccount",
    icon: "nav-cardmanage",
    uid: "/healthaccount",
    type: 2,
    children: [
      {
        name: "用户账户管理",
        path: "account",
        uid: "/healthaccount/account",
        type: 2,
      },
      {
        name: "用户账户管理",
        path: "useraccount",
        uid: "/healthaccount/useraccount",
        type: 2,
      },
      {
        name: "开户流水管理",
        path: "flow",
        uid: "/healthaccount/flow",
        type: 2,
      },
      {
        name: "交易管理",
        path: "trade",
        uid: "/healthaccount/trade",
        type: 2,
      },
      {
        name: "交易管理",
        path: "usertrade",
        uid: "/healthaccount/usertrade",
        type: 2,
      },
      {
        name: "调账管理",
        path: "adjust",
        uid: "/healthaccount/adjust",
        type: 2,
      },
    ],
  },
  {
    name: "渠道对账管理",
    path: "reconciliation",
    icon: "nav-prescription",
    uid: "/reconciliation",
    type: 2,
    children: [
      {
        name: "渠道对账",
        path: "fund",
        uid: "/reconciliation/fund",
        type: 2,
      },
      {
        name: "差错管理",
        path: "error-manage",
        uid: "/reconciliation/error-manage",
        type: 2,
      },
      {
        name: "挂账管理",
        path: "credit-manage",
        uid: "/reconciliation/credit-manage",
        type: 2,
      },
      {
        name: "对账任务",
        path: "channel-log",
        uid: "/reconciliation/channel-log",
        type: 2,
      },
    ],
  },
];

export default menus;
